baseURL = "https://blog.natalienguyen.dev/"
languageCode = "en-us"
title = "Natalie Nguyen ğŸ‰"
description = "I work in IT"

theme=["hugo-paper", "hugo-paper-amended"]

googleAnalytics = "UA-154580558-1"
