baseURL = "https://blog.natalienguyen.dev"
languageCode = "en-us"
title = "Natalie Nguyen ğŸ‰"
description = "I work in IT"

theme=["terminal","hugo-paper-amended", "hugo-paper"]

googleAnalytics = "UA-154580558-1"
